#!/usr/bin/env bash

validator=$1
short=$2

VALIDATORS=( "is-my-json-valid" "jjv" "jsonschema" "skeemas" "tv4" "z-schema" )

function mocha_test()
{
    export JSC_VALIDATOR=$1
    ./node_modules/.bin/mocha --reporter=spec spec/*.spec.js
    export JSC_VALIDATOR=""
}

function schema_test()
{
    local validator=$1
    local short=$2
    sed -e "s/\${VALIDATOR}/$validator/" spec/adapter.template.js > spec/adapter.js
    local results=$(json-schema-tests "spec/adapter.js")
    if [[ $short == "true" ]]; then
        echo "${validator}: $(echo "$results" | grep -i 'passed')"
    else
        echo $'\n\n'"Testing ${validator}"$'\n'
        echo "$results"
    fi
}

if [[ $validator == "" || $validator == "--full" ]]; then
    mocha_test
    [[ "$validator" == "--full" ]] && short="" || short="true"
    for val in "${VALIDATORS[@]}"; do
        schema_test $val $short
    done
else
    mocha_test $validator
    [[ "$short" == "--short" ]] && short="true" || short=""
    schema_test $validator $short
fi
