#!/usr/bin/env bash

validator=$1

VALIDATORS=( "is-my-json-valid" "jjv" "tv4" )

function mocha_test()
{
    export JSC_VALIDATOR=$1
    ./node_modules/.bin/mocha --reporter=spec spec/*.spec.js
    export JSC_VALIDATOR=""
}

function schema_test()
{
    local validator=$1
    sed -e "s/\${VALIDATOR}/$validator/" spec/adapter.template.js > spec/adapter.js
    json-schema-tests "spec/adapter.js"
    rm spec/adapter.js
}

if [[ $validator == "" || $validator == "--full" ]]; then
    mocha_test
    for val in "${VALIDATORS[@]}"; do
        results=$(schema_test $val)
        if [[ $validator == "--full" ]]; then
            echo $'\n\n'"Testing ${val}"$'\n'
            echo "$results"
        else
            echo "${val}: $(echo "$results" | grep -i 'passed')"
        fi
    done
else
    mocha_test $validator
    schema_test $validator
fi
